name: flutter_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
